import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Routes(props) {
    const { nodes, materials } = useGLTF('./models/routes.glb')
    return (
        <group {...props} dispose={null} scale={0.9}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Straight253.geometry}
                material={materials['Paths.001']}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.L_Turn176.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.L_Turn177.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.L_Turn178.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.L_Turn179.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.L_Turn180.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.L_Turn181.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.L_Turn182.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.L_Turn183.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight240.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight241.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight242.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight243.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight244.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight245.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight246.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight247.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight248.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight249.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight250.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight252.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight254.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight255.geometry}
                    material={materials['Paths.001']}
                />
            </mesh>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Straight258.geometry}
                material={materials['Paths.001']}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.L_Turn184.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.L_Turn185.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.L_Turn186.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.L_Turn187.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.L_Turn188.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.L_Turn189.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.L_Turn190.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.L_Turn191.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight256.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight257.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight259.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight260.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight261.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight262.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight263.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight264.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight265.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight266.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight267.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight268.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight269.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight270.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight271.geometry}
                    material={materials['Paths.001']}
                />
            </mesh>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Straight273.geometry}
                material={materials['Paths.001']}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.L_Turn192.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.L_Turn193.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.L_Turn194.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.L_Turn195.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.L_Turn196.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.L_Turn197.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.L_Turn198.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.L_Turn199.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight272.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight274.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight275.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight276.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight277.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight278.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight279.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight280.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight281.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight282.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight283.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight284.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight285.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight286.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight287.geometry}
                    material={materials['Paths.001']}
                />
            </mesh>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Straight289.geometry}
                material={materials['Paths.001']}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.L_Turn200.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.L_Turn201.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.L_Turn202.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.L_Turn203.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.L_Turn204.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.L_Turn205.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.L_Turn206.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.L_Turn207.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight288.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight290.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight291.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight292.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight293.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight294.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight295.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight296.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight297.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight298.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight299.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight300.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight301.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight302.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight303.geometry}
                    material={materials['Paths.001']}
                />
            </mesh>
        </group>
    )
}

useGLTF.preload('./models/routes.glb')