import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Routes(props) {
    const { nodes, materials } = useGLTF('./models/routes.glb')
    return (
        <group {...props} dispose={null} scale={0.3}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Straight701.geometry}
                material={materials['Paths.001']}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.L_Turn400.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.L_Turn401.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.L_Turn402.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.L_Turn403.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.L_Turn404.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.L_Turn405.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.L_Turn406.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.L_Turn407.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight688.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight689.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight690.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight691.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight692.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight693.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight694.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight695.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight696.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight697.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight698.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight699.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight700.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight702.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight703.geometry}
                    material={materials['Paths.001']}
                />
            </mesh>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Straight706.geometry}
                material={materials['Paths.001']}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.L_Turn408.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.L_Turn409.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.L_Turn410.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.L_Turn411.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.L_Turn412.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.L_Turn413.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.L_Turn414.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.L_Turn415.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight704.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight705.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight707.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight708.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight709.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight710.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight711.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight712.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight713.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight714.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight715.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight716.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight717.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight718.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight719.geometry}
                    material={materials['Paths.001']}
                />
            </mesh>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Straight721.geometry}
                material={materials['Paths.001']}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.L_Turn416.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.L_Turn417.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.L_Turn418.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.L_Turn419.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.L_Turn420.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.L_Turn421.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.L_Turn422.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.L_Turn423.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight720.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight722.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight723.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight724.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight725.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight726.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight727.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight728.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight729.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight730.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight731.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight732.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight733.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight734.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight735.geometry}
                    material={materials['Paths.001']}
                />
            </mesh>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Straight737.geometry}
                material={materials['Paths.001']}>
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.L_Turn424.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.L_Turn425.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.L_Turn426.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.L_Turn427.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.L_Turn428.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.L_Turn429.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.L_Turn430.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.L_Turn431.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight736.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight738.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight739.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight740.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight741.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight742.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight743.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight744.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight745.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight746.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight747.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight748.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight749.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight750.geometry}
                    material={materials['Paths.001']}
                />
                <mesh
                    castShadow
                    receiveShadow
                    geometry={nodes.Straight751.geometry}
                    material={materials['Paths.001']}
                />
            </mesh>
        </group>
    )
}

useGLTF.preload('./models/routes.glb')
